name:                mud
version:             0.1.0.0
github:              "mitsuchi/mud"
license:             BSD3
author:              "Tatsuo Mitsuchi"
maintainer:          "t.mitsuchi3@gmail.com"
copyright:           "2019 Tatsuo Mitsuchi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mitsuchi/mud#readme>

dependencies:
- base
- megaparsec
- parser-combinators
- containers
- mtl
- HUnit
- test-framework
- test-framework-hunit

library:
  source-dirs: src

executables:
  mud:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mud

tests:
  mud-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mud
